# ==============================================================
# 1. SERVER CONFIGURATION
# ==============================================================
server:
  port: 8080
  servlet:
    context-path: /  # Đường dẫn gốc (VD: http://localhost:8080/)

# ==============================================================
# 2. SPRING CONFIGURATION
# ==============================================================
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: Axbycz789
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # --- FILE UPLOAD (Chuẩn bị cho việc up ảnh món ăn) ---
  servlet:
    multipart:
      max-file-size: 10MB      # Giới hạn 1 file
      max-request-size: 10MB   # Giới hạn tổng request

# ==============================================================
# 3. APP CUSTOM CONFIGURATION (JWT)
# ==============================================================
app:
  # Chuỗi bí mật để mã hóa Token.
  # (Đây là chuỗi Hex 512-bit mẫu, bạn có thể giữ nguyên hoặc random lại)
  jwtSecret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

  # Thời gian hết hạn Token (tính bằng mili-giây)
  # 86400000 ms = 24 giờ
  jwtExpirationMs: 86400000