# ==============================================================
# 1. SERVER CONFIGURATION
# ==============================================================
server:
  port: 8080
  servlet:
    context-path: /  # Đường dẫn gốc (VD: http://localhost:8080/)

# ==============================================================
# 2. SPRING CONFIGURATION
# ==============================================================
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # --- FILE UPLOAD (Chuẩn bị cho việc up ảnh món ăn) ---
  servlet:
    multipart:
      max-file-size: 10MB      # Giới hạn 1 file
      max-request-size: 10MB   # Giới hạn tổng request

# ==============================================================
# 3. APP CUSTOM CONFIGURATION (JWT)
# ==============================================================
app:
  # Chuỗi bí mật để mã hóa Token.
  # (Đây là chuỗi Hex 512-bit mẫu, bạn có thể giữ nguyên hoặc random lại)
  jwtSecret: ${JWT_SECRET}

  # Thời gian hết hạn Token (tính bằng mili-giây)
  # 86400000 ms = 24 giờ
  jwtExpirationMs: 86400000

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

payment:
  vnpay:
    url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html" # URL này cố định, không cần ẩn
    api-url: "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction" # Cố định
    tmn-code: ${VNPAY_TMN_CODE}       # <--- Chờ biến môi trường
    hash-secret: ${VNPAY_HASH_SECRET} # <--- Chờ biến môi trường
    return-url: ${VNPAY_RETURN_URL}   # <--- URL trả về (Local khác, VPS khác)

frontend:
  url: "http://localhost:5173"